### ISSUE TITLE
Allow using read-only volume without errors

### ISSUE THREAD

**Issue by rugk** [linuxserver/docker-ddclient#48]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Desired Behavior

You should support read-only images without any errors:
```
---
version: "2.1"
services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - <path to data>:/config:ro
    restart: unless-stopped
```

The permission configuration (setting etc.) may be done once, 

This is a security feature.

## Current Behavior

If you [use the current config](https://github.com/linuxserver/docker-ddclient#docker-compose-recommended), you suggest `- <path to data>:/config` everything works.

However when you mount the volume read-only, you get errors such as this:
> chmod: changing permissions of '/config/ddclient.conf': Read-only file system

The container still works, but this is IMHO not good.

## Alternatives Considered

* Mount image writable:
   For an initial configuration/chmod-thing this may be acceptable, but `ddclient` itself actually does only need read-only access to the config and IMHO thus should also be mounted/mountable as such.
