### ISSUE TITLE
Continuous disk IO of "s6-supervise ddclient" process

### ISSUE THREAD

**Issue by extrafein** [linuxserver/docker-ddclient#57]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior
Only some disk IO in the docker DDclient container warm up phase ... then no disk IO at all.

## Current Behavior
```
> iotop -o
Total DISK READ:         0.00 B/s | Total DISK WRITE:        16.85 K/s
Current DISK READ:       0.00 B/s | Current DISK WRITE:      13.48 K/s
    TID  PRIO  USER     DISK READ  DISK WRITE  SWAPIN     IO>    COMMAND
 363578 ?sys root        0.00 B/s   16.85 K/s  0.00 %  0.00 % s6-supervise ddclient
```

## Steps to Reproduce
Sorry, nothing special here.
1. install container: image: lscr.io/linuxserver/ddclient   with simple bridge setup
2. run the container

## Environment
**OS:** DietPi
**CPU architecture:** arm64
**How docker service was installed:**
from the official docker repo

## Command used to create docker container (run/create/compose/screenshot)
compose
```
version: "3.7"

networks:
  web:
    external:
      name: web

services:
  ddclient:
    image: lscr.io/linuxserver/ddclient
    container_name: ddclient
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 64M
    networks:
      - web
    volumes:
      - ./config:/config
      - ./scripts:/scripts
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    restart: always
    labels:
      - com.centurylinklabs.watchtower.enable=true

```
## Docker logs
````
[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing...
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 02-tamper-check: executing...
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing...
-------------------------------------
          _         ()
         | |  ___   _    __
         | | / __| | |  /  \
         | | \__ \ | | | () |
         |_| |___/ |_|  \__/
Brought to you by linuxserver.io
-------------------------------------
To support LSIO projects visit:
https://www.linuxserver.io/donate/
-------------------------------------
GID/UID
-------------------------------------
User uid:    1000
User gid:    1000
-------------------------------------
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 90-custom-folders: executing...
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing...
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
Setting up watches.
Watches established.
```

**Comment by tobbenb** [comment]
I'm not sure I understand what the issue is here. 
Do you mean there should be no disk I/O after the container starts up?

16.85 K/s doesn't seem high to me.

**Comment by extrafein** [comment]
This is the accumulation of the process writes within a minute.
In comparison to resilio-sync (in wait state) this is huge for a process which only
updates the dns-server once or twice a day and it is resting.
And I want to give my SSD and/or SDCard a "break".

```
Total DISK READ:         0.00 B/s | Total DISK WRITE:        65.37 K/s
Current DISK READ:       0.00 B/s | Current DISK WRITE:     147.94 K/s
    TID  PRIO  USER     DISK READ DISK WRITE>  SWAPIN      IO    COMMAND
1671315 ?sys root          0.00 B   1344.00 K  0.00 %  0.00 % s6-supervise ddclient
     94 ?sys root          0.00 B    760.00 K  0.00 %  0.08 % [jbd2/sda2-8]
1148183 ?sys dietpi        0.00 B    372.00 K  0.00 %  0.00 % rslsync --nodaemon --config /config/sync.conf
```

Would be great if you can look into it.

Thank you in advance.

**Comment by j0nnymoe** [comment]
Could you try removing the extra stuff you've added to the compose and see if you get the same outcome? (Scripts volume and resource limits)

**Comment by extrafein** [comment]
This is the simplified YAML and the behaviour is just the same.
Also forced usage of lscr.io/linuxserver/ddclient:arm64v8-latest.
No change.

```
version: "3.7"

networks:
  web:
    external:
      name: web

services:
  ddclient:
    image: lscr.io/linuxserver/ddclient
    container_name: ddclient
    networks:
      - web
    volumes:
      - ./config:/config
    environment:
      - TZ=Europe/Berlin
      - PUID=1000
      - PGID=1000
    restart: always

```
