### ISSUE TITLE
Latest v3.9.1-ls96 is broken 

### ISSUE THREAD

**Issue by fredbcode** [linuxserver/docker-ddclient#59]
Hello
```
docker logs compose_ddclient_1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
s6-overlay-suexec: fatal: can only run as pid 1
```
```
5f2af5a7f05d   linuxserver/ddclient                                                   "/init"                  12 seconds ago   Restarting (100) 3 seconds ago                                  compose_ddclient_1
```

**Comment by Roxedus** [comment]
Do you have init set to true in daemon.json or your compose/run (which you are supposed to provide when opening a issue)

**Comment by fredbcode** [comment]
Sorry

It's just an upgrade form previous version, same issue without configuration file 

```
  ddclient:
    image: linuxserver/ddclient
    restart: always
       volumes:
       - ./ddclient/ddclientnas.conf:/config/ddclient.conf 

```
