### ISSUE TITLE
"unrecognized keyword 'usev6'" and failure to set IPv6 address

### ISSUE THREAD

**Issue by truppelito** [linuxserver/docker-ddclient#60]
[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

------------------------------

## Expected Behavior

I'm running this image on a raspberry pi with the following config file:

```
force=yes
ssl=yes
daemon=5m
protocol=dyndns2
usev6=if
if=eth0
server=dynv6.com
login=none
password='xxx'
xxx.dynv6.net
```

I expected ddclient to update the IPv6 address. In fact, by installing ddclient directly with `sudo apt-get install ddclient` and running it with `sudo ddclient -file /path-to-config-file/ddclient.conf` I get this expected behaviour.

## Current Behavior
By executing `ddclient -file /config/ddclient.conf` in the container I get the following output:

```
WARNING:  file /config/ddclient.conf, line 5: unrecognized keyword 'usev6' (ignored)
WARNING:  file /config/ddclient.conf, line 5: unrecognized keyword 'usev6' (ignored)
WARNING:  found neither ipv4 nor ipv6 address
WARNING:  unable to determine IP address
```

## Steps to Reproduce
Explained above.

## Environment
**OS:** Linux raspberrypi 5.15.61-v8+
**CPU architecture:** arm64
**How docker service was installed:** Using apt-get

## Command used to create docker container (run/create/compose/screenshot)

```
  ddclient:
    image: lscr.io/linuxserver/ddclient
    container_name: ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    volumes:
      - ./ddclient-config:/config
    restart: unless-stopped

```

## Docker logs

A very large number of copies of this line:

`WARNING:  file /ddclient.conf, line 3: unrecognized keyword 'usev6' (ignored)`
