### ISSUE TITLE
[BUG] unable to start container when running with docker secrets/configs

### ISSUE THREAD

**Issue by alanchianggit** [linuxserver/docker-ddclient#70]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When running stack using docker-compose file such as
```
version: "3.8"

services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    configs:
      - source: ddclient.conf
        target: /config/ddclient.conf
    environment:
      TZ: 'America/Vancouver'
      PGID: 1000
      PUID: 1000
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager

configs:
  ddclient.conf:
    external: true
```

the configs are being passed in but the logs suggests that it cannot be initiated

> $ docker logs 629e
> [migrations] started
> [migrations] no migrations found
> ───────────────────────────────────────
> 
>       ██╗     ███████╗██╗ ██████╗
>       ██║     ██╔════╝██║██╔═══██╗
>       ██║     ███████╗██║██║   ██║
>       ██║     ╚════██║██║██║   ██║
>       ███████╗███████║██║╚██████╔╝
>       ╚══════╝╚══════╝╚═╝ ╚═════╝
> 
>    Brought to you by linuxserver.io
> ───────────────────────────────────────
> 
> To support LSIO projects visit:
> https://www.linuxserver.io/donate/
> 
> ───────────────────────────────────────
> GID/UID
> ───────────────────────────────────────
> 
> User UID:    1000
> User GID:    1000
> ───────────────────────────────────────
> 
> chown: changing ownership of '/config/ddclient.conf': Read-only file system
> chmod: changing permissions of '/config/ddclient.conf': Read-only file system
> s6-rc: warning: unable to start service init-ddclient-config: command exited 1
> **** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
> **** The app may not work properly and we will not provide support for it. ****
> 

I've tried numerous PID/GID/Mode assignments to make permissions wider with no luck.

### Steps To Reproduce

1. create config using such as 
`docker config create ddclient.conf ~/ddclient.conf`

3. deploy stack with compose file such as 
```
version: "3.8"

services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    configs:
      - source: ddclient.conf
        target: /config/ddclient.conf
    environment:
      TZ: 'America/Vancouver'
      PGID: 1000
      PUID: 1000
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager

configs:
  ddclient.conf:
    external: true
```

### Environment

```markdown
- OS: Linux (Rocky Server 8)
- How docker service was installed: docker (swarm)
```

### CPU architecture

x86-64

### Docker creation

```bash
version: "3.8"

services:
  ddclient:
    image: ghcr.io/linuxserver/ddclient
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped
    configs:
      - source: ddclient.conf
        target: /config/ddclient.conf
    environment:
      TZ: 'America/Vancouver'
      PGID: 1000
      PUID: 1000
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager

configs:
  ddclient.conf:
    external: true
```

### Container logs

```bash
$ docker logs 629e
[migrations] started
[migrations] no migrations found
───────────────────────────────────────

      ██╗     ███████╗██╗ ██████╗
      ██║     ██╔════╝██║██╔═══██╗
      ██║     ███████╗██║██║   ██║
      ██║     ╚════██║██║██║   ██║
      ███████╗███████║██║╚██████╔╝
      ╚══════╝╚══════╝╚═╝ ╚═════╝

   Brought to you by linuxserver.io
───────────────────────────────────────

To support LSIO projects visit:
https://www.linuxserver.io/donate/

───────────────────────────────────────
GID/UID
───────────────────────────────────────

User UID:    1000
User GID:    1000
───────────────────────────────────────

chown: changing ownership of '/config/ddclient.conf': Read-only file system
chmod: changing permissions of '/config/ddclient.conf': Read-only file system
s6-rc: warning: unable to start service init-ddclient-config: command exited 1
**** Permissions could not be set. This is probably because your volume mounts are remote or read-only. ****
**** The app may not work properly and we will not provide support for it. ****
```

**Comment by aptalca** [comment]
We don't support config mapping. Our container expects the config file to be within the `/config` folder that is expected to be bind mounted with rw.

With that said, the log messages are clear. Init could not fix the perms on the file, so it may or may not work. We don't know.

**Comment by alanchianggit** [comment]
ok thanks, if possible will look forward to this feature

**Comment by Roxedus** [comment]
No. Our images are not focused on catering to that use case.

**Comment by rachelf42** [comment]
this can be achieved by applying the fix in [#29](https://github.com/linuxserver/docker-ddclient/issues/29#issuecomment-571118757), ie changing this section of the compose file:
```
services:
  ddclient:
    configs:
      - source: ddclient.conf
        target: /config/ddclient.conf
```
to this:
```
services:
  ddclient:
    configs:
      - source: ddclient.conf
        target: /defaults/ddclient.conf
```
i do think this should be at least mentioned in the docs somewhere, but its an easy fix on our ends without any container changes
