### ISSUE TITLE
Continuous disk IO of "s6-supervise ddclient" process

### ISSUE THREAD

**Issue by phatpaul** [linuxserver/docker-ddclient#89]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

This is the same issue as #57 but that was auto closed and locked.  The problem still persists, so why close the issue just because nobody bothered to fix it?

Constant disk write activity for no good reason.  I suspect this is what trashed my eMMC flash chip on my SBC.  I finally noticed it after migrating to a new SBC that has a disk activity light.

### Expected Behavior

This docker could be implemented in a way that doesn't do unecessary writes to storage every second.

There was a similar issue reported on another project. Maybe there's a quick fix that's applicable for this one. 
Please see https://github.com/NginxProxyManager/nginx-proxy-manager/issues/2741 
https://github.com/NginxProxyManager/nginx-proxy-manager/pull/3044/files

### Steps To Reproduce

Just the normal use case.

### Environment

```markdown
- OS: Ubuntu 20.04
- How docker service was installed: apt install
```

### CPU architecture

arm64

### Docker creation

```bash
services:
  ddclient:
    image: linuxserver/ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config/:/config
```
```


### Container logs

```bash
Total DISK READ:         0.00 B/s | Total DISK WRITE:         4.87 K/s
Current DISK READ:       0.00 B/s | Current DISK WRITE:       7.31 K/s
    TID  PRIO  USER     DISK READ DISK WRITE>    COMMAND
3250337 be/4 root        0.00 B/s    4.87 K/s s6-supervise svc-ddclient
```

**Comment by phatpaul** [comment]
I noticed the new read-only feature and tried it. That seems to work around the issue.
My new docker-compose.yml
```yml
services:
  ddclient:
    image: linuxserver/ddclient
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ./config/:/config
    tmpfs:
      - /run:exec
      - /tmp
    read_only: true
```
Perhaps that could be mentioned in this container readme.
