### ISSUE TITLE
[BUG] FILE__varname is not parsed in the container

### ISSUE THREAD

**Issue by brumik** [linuxserver/docker-ddclient#90]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When I set: 
```
environment:
  FILE__PASS: /run/secrets/ddclient_password
```

I can see the evironment variable `FILE__PASS` set in the container to the path but the `PASS` is undefined.

[Documentation about the feature](https://github.com/linuxserver/docker-ddclient?tab=readme-ov-file#environment-variables-from-files-docker-secrets)

### Expected Behavior

The `PASS` contains the contents of the `/run/secrets/ddclient_password` file.

### Steps To Reproduce

1. Create a secret in `./secrets/ddclient/password` as a simple string `xxxxxxx` for example
2.
```
secrets:
  ddclient_password:
    file: ./secrets/ddclient/password

services:
  ddclient:
    image: lscr.io/linuxserver/ddclient:latest
    container_name: ddclient
    environment:
      TZ: $TZ
      PUID: $PUID
      PGID: $PGID
      FILE__PASS: /run/secrets/ddclient_password
    secrets:
      - ddclient_password
    volumes:
      - ../appdata/ddclient:/config
    restart: unless-stopped
```
3. After starting the container jump into it `docker compose exec ddclient sh`
4. See that `PASS` variable is undefined

### Environment

```markdown
- OS: Ubutnu & NixOs
- How docker service was installed: official documetation / nixos config by virtualization
```

### CPU architecture

x86-64

### Docker creation

```bash
`docker compose up ddclient`
```

### Container logs

If we set up the env variable to be used as password then following code:

```conf
# ddclient.conf
password_env=PASS

```

```bash
ddclient  | WARNING:  null password specified for host xxxxx
```
